// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

/*
Package users is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	GetRequest
	User
*/
package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceService interface {
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*User, error)
}

type userServiceService struct {
	c           client.Client
	serviceName string
}

func UserServiceServiceClient(serviceName string, c client.Client) UserServiceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "users"
	}
	return &userServiceService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceService) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Get", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Get(context.Context, *GetRequest, *User) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Get(ctx context.Context, in *GetRequest, out *User) error {
	return h.UserServiceHandler.Get(ctx, in, out)
}
